<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmi:id="HSM" name="TwoLayerMM" nsURI="TwoLayerMM" nsPrefix="twolayer">
  <eClassifiers xsi:type="ecore:EClass" name="MEtop">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" upperBound="-1" eType="//MEchild"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MEchild">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eStructuralFeatures xsi:type="ecore:EReference" name="metops" upperBound="-1" eType="//MEtop" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mechildren" upperBound="-1" eType="//MEchild" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
