<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="UML" nsURI="UML" nsPrefix="uml">
  <eClassifiers xsi:type="ecore:EClass" name="Class">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="acyclic_inheritance" value="not self->closure(super)->includes(self)"/>
      <details key="unique_names" value="self.attributes->forAll(x | self.attributes->forAll(y | x = y or x.name &lt;> y.name))"/>
    </eAnnotations>
    <eOperations name="setName">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="post_set_name" value="self.name = n"/>
        <details key="post_frame_condition_package" value="Package.allInstances@pre() = Package.allInstances()"/>
        <details key="post_frame_condition_package_classes" value="Package.allInstances()->forAll(x | x.classes@pre = x.classes)"/>
        <details key="post_frame_condition_package_name" value="Package.allInstances()->forAll(x | x.name@pre = x.name)"/>
        <details key="post_frame_condition_attribute" value="Attribute.allInstances@pre() = Attribute.allInstances()"/>
        <details key="post_frame_condition_attribute_name" value="Attribute.allInstances()-> forAll(x | x.name@pre = x.name)"/>
        <details key="post_frame_condition_class" value="Class.allInstances@pre() = Class.allInstances()"/>
        <details key="post_frame_condition_class_attributes" value="Class.allInstances()-> forAll(x | x.attributes@pre = x.attributes)"/>
        <details key="post_frame_condition_class_persistent" value="Class.allInstances()-> forAll(x | x.persistent@pre = x.persistent)"/>
        <details key="post_frame_condition_class_super" value="Class.allInstances()-> forAll(x | x.super@pre = x.super)"/>
        <details key="post_frame_condition_class_name" value="Class.allInstances()-> forAll(x | x.name@pre = x.name or x = self)"/>
      </eAnnotations>
      <eParameters name="n" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addAttribute">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="post_b" value="Package.allInstances()->forAll(x | x.classes@pre = x.classes)"/>
        <details key="post_e" value="Package.allInstances()->forAll(x | x.name@pre = x.name)"/>
        <details key="post_f" value="Attribute.allInstances@pre()-> forAll(x | x.name@pre = x.name)"/>
        <details key="post_g" value="Class.allInstances()-> forAll(x | x.attributes@pre = x.attributes or x = self)"/>
        <details key="post_h" value="Class.allInstances()-> forAll(x | x.persistent@pre = x.persistent)"/>
        <details key="post_c" value="Class.allInstances@pre() = Class.allInstances()"/>
        <details key="post_d" value="Attribute.allInstances@pre()->forAll(x | Attribute.allInstances()->includes(x))"/>
        <details key="post_i" value="Class.allInstances()-> forAll(x | x.super@pre = x.super)"/>
        <details key="post_z" value="Package.allInstances@pre() = Package.allInstances()"/>
        <details key="post_ff" value="Class.allInstances()-> forAll(x | x.name@pre = x.name)"/>
        <details key="post_c" value="Attribute.allInstances()->one(x | x.oclIsNew() and x.name = n and self.attributes->includes(x))"/>
      </eAnnotations>
      <eParameters name="n" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="remAttribute">
      <eParameters name="n" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="setPersistent">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="post_b" value="Package.allInstances()->forAll(x | x.classes@pre = x.classes)"/>
        <details key="post_e" value="Package.allInstances()->forAll(x | x.name@pre = x.name)"/>
        <details key="post_f" value="Attribute.allInstances()-> forAll(x | x.name@pre = x.name)"/>
        <details key="post_g" value="Class.allInstances()-> forAll(x | x.attributes@pre = x.attributes)"/>
        <details key="post_h" value="Class.allInstances()-> forAll(x | x.persistent@pre = x.persistent or x = self)"/>
        <details key="post_c" value="Class.allInstances@pre() = Class.allInstances()"/>
        <details key="post_d" value="Attribute.allInstances@pre() = Attribute.allInstances()"/>
        <details key="post_i" value="Class.allInstances()-> forAll(x | x.super@pre = x.super)"/>
        <details key="post_z" value="Package.allInstances@pre() = Package.allInstances()"/>
        <details key="post_ff" value="Class.allInstances()-> forAll(x | x.name@pre = x.name)"/>
      </eAnnotations>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="persistent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//Attribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="super" eType="#//Class"
        eOpposite="#//Class/child"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="namespace" lowerBound="1"
        eType="#//Package" eOpposite="#//Package/classes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="child" upperBound="-1"
        eType="#//Class" eOpposite="#//Class/super"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute">
    <eOperations name="setName">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
        <details key="post_a" value="self.name = n"/>
        <details key="post_b" value="Package.allInstances()->forAll(x | x.classes@pre = x.classes)"/>
        <details key="post_e" value="Package.allInstances()->forAll(x | x.name@pre = x.name)"/>
        <details key="post_f" value="Class.allInstances()-> forAll(x | x.name@pre = x.name)"/>
        <details key="post_g" value="Class.allInstances()-> forAll(x | x.attributes@pre = x.attributes)"/>
        <details key="post_h" value="Class.allInstances()-> forAll(x | x.persistent@pre = x.persistent)"/>
        <details key="post_c" value="Class.allInstances@pre() = Class.allInstances()"/>
        <details key="post_d" value="Attribute.allInstances@pre() = Attribute.allInstances()"/>
        <details key="post_i" value="Class.allInstances()-> forAll(x | x.super@pre = x.super)"/>
        <details key="post_z" value="Package.allInstances@pre() = Package.allInstances()"/>
        <details key="post_ff" value="Attribute.allInstances()-> forAll(x | x.name@pre = x.name or x = self)"/>
      </eAnnotations>
      <eParameters name="n" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Package">
    <eAnnotations source="Echo/Gen">
      <details key="gen_linear" value="self.classes->one(x | x.super->isEmpty())"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="unique_names" value="self.classes->forAll(x | self.classes->forAll(y | x = y or x.name &lt;> y.name))"/>
    </eAnnotations>
    <eOperations name="setName">
      <eAnnotations source="back">
        <details key="post_a" value="self.name = n"/>
        <details key="post_b" value="self.classes@pre = self.classes"/>
        <details key="post_e" value="Attribute.allInstances()->forAll(x | x.name@pre = x.name)"/>
        <details key="post_f" value="Class.allInstances()-> forAll(x | x.name@pre = x.name)"/>
        <details key="post_g" value="Class.allInstances()-> forAll(x | x.attributes@pre = x.attributes)"/>
        <details key="post_h" value="Class.allInstances()-> forAll(x | x.persistent@pre = x.persistent)"/>
        <details key="post_c" value="Class.allInstances@pre() = Class.allInstances()"/>
        <details key="post_d" value="Attribute.allInstances@pre() = Attribute.allInstances()"/>
        <details key="post_i" value="Class.allInstances()-> forAll(x | x.super@pre = x.super)"/>
        <details key="post_z" value="Package.allInstances@pre() = Package.allInstances()"/>
      </eAnnotations>
      <eParameters name="n" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="addClass">
      <eAnnotations source="back">
        <details key="post_e" value="Attribute.allInstances()->forAll(x | x.name@pre = x.name)"/>
        <details key="post_c" value="Class.allInstances()->one(x | x.oclIsNew() and x.name = n and self.classes->includes(x))"/>
        <details key="post_d" value="Attribute.allInstances@pre() = Attribute.allInstances()"/>
        <details key="post_a" value="Class.allInstances@pre()->forAll(x | x.name@pre = x.name and x.attributes@pre = x.attributes)"/>
        <details key="post_cc" value="Package.allInstances@pre()->forAll(x | Package.allInstances()->includes(x) and x.classes@pre->forAll(y | x.classes->includes(y)) and x.name@pre = x.name)"/>
      </eAnnotations>
      <eParameters name="n" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="remClass">
      <eParameters name="n" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="New"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classes" upperBound="-1"
        eType="#//Class" containment="true" eOpposite="#//Class/namespace"/>
  </eClassifiers>
</ecore:EPackage>
